# Generated by Django 4.2.17 on 2025-01-07 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('instrumento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilBanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('anio_formacion', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroBanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=100, null=True)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.banda')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.miembro')),
            ],
        ),
        migrations.AddField(
            model_name='banda',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.perfilbanda'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField()),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.banda')),
            ],
        ),
    ]
